export enum Config {
  ServerPort = "server_port",
  MongoUri = "mongo_uri",
  Neo4jUri = "neo4j_uri",
  Neo4jUser = "neo4j_user",
  Neo4jPassword = "neo4j_password",
  RedisUrl = "redis_url",
  OpenrouterApiKey = "openrouter_api_key",
  OpenrouterModel = "openrouter_model",
  OpenrouterFallbackModel1 = "openrouter_fallback_model_1",
  OpenrouterFallbackModel2 = "openrouter_fallback_model_2",
  OpenrouterFallbackModel3 = "openrouter_fallback_model_3",
  OpenrouterFallbackModel4 = "openrouter_fallback_model_4",
  ConcurrencyGithub = "concurrency.github",
  LogLevel = "log_level",
  LogRetentionDays = "log_retention_days",
  LlmCacheEnabled = "llm_cache_enabled",
}
